#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/lircd
NAME=lircd
PIDFILE=/var/run/lircd.pid
LIRCD_ARGS="-o /dev/lircd -P $PIDFILE"

if [ -f /etc/lirc/hardware.conf ];then
        . /etc/lirc/hardware.conf
fi

if [ -n "$REMOTE_DRIVER" ]; then
	LIRCD_ARGS="$LIRCD_ARGS --driver=$REMOTE_DRIVER"
fi

if [ -n "$REMOTE_DEVICE" ]; then
	LIRCD_ARGS="$LIRCD_ARGS --device=$REMOTE_DEVICE"
fi

start() {
	mkdir -p /var/run/vsftpd/empty

	echo -n "starting $NAME..."
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $LIRCD_ARGS > /dev/null 2>&1
	if [ "$?" = "0" ]; then
		echo "done"
	else
		echo "failed $?"
		exit 1
	fi
}

stop() {
	echo -n "stopping $NAME..."
	start-stop-daemon -K -p $PIDFILE > /dev/null 2>&1
	if [ "$?" = "0" ]; then
		echo "done"
	else
		echo "failed $?"
		exit 1
	fi
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	$0 stop
	sleep 1
	$0 start
	;;
*)
	echo "usage: $0 {start|stop|restart}"
esac

exit 0

