#!/bin/sh

echo "Stopping services ..."
for k in /etc/rc.d/K*; do
	if [ -x $k ]; then
		$k stop
	fi
done


# Kill all processes.
echo -n "Sending all processes the TERM signal..."
killall5 -15
echo "done."
sleep 1
echo -n "Sending all processes the KILL signal..."
killall5 -9
echo "done."

