#!/bin/sh
#
# /etc/init.d/rcS
#

mount -t proc none /proc

if grep -q "quiet" /proc/cmdline; then
	exec 1>/dev/null
fi

if [ ! -c /dev/console ]; then
	rm -f /dev/console
	mknod /dev/console c 5 1 
fi

echo -n "mounting filesystems..."
mount -a 2>/dev/null
echo "done."

# loadkmap < /etc/boottime.kmap

# set hostname
test -e /etc/hostname && hostname -F /etc/hostname

echo "running rc.d services..."
for s in /etc/rc.d/S*; do
	if [ -x $s ]; then
		$s start
	fi
done
