#!/bin/sh

#export XBMC_BASE=/opt/xbmc
#export XBMC_HOME=/opt/xbmc/share/xbmc
#export PATH=$PATH:/opt/xbmc/bin
export PATH=/usr/bin:/bin:/usr/sbin:/sbin
export HOME=/root

export LD_LIBRARY_PATH=$XBMC_BASE/lib:/opt/vc/lib:/usr/lib/mysql:$LD_LIBRARY_PATH

xbmc_start()
{
	# detect & backup screen resolution
	RESOL=`fbset | grep mode | grep -v endmode | sed "s/\"/%/" | cut -d'%' -f2 | cut -d'-' -f1`
	XRES=`echo $RESOL | cut -d'x' -f1`
	YRES=`echo $RESOL | cut -d'x' -f2`

	# hide console
	echo 0 > /sys/class/vtconsole/vtcon1/bind
	fbset -xres 1 -yres 1 -vxres 1 -vyres 1

	# start xbmc
	/usr/lib/xbmc/xbmc.bin -standalone -fs

	RET=$?
	echo $RET

	case "$RET" in
	   0)
		# restore console & screen resolution when xbmc ends
		fbset -xres ${XRES} -yres ${YRES}
		echo 1 > /sys/class/vtconsole/vtcon1/bind
		;;
	   64)
		poweroff
		;;
	   66)
	  	reboot
		;;
	   *)
		# restore console & screen resolution when xbmc ends
		fbset -xres ${XRES} -yres ${YRES}
		echo 1 > /sys/class/vtconsole/vtcon1/bind
		echo "Abnormal Exit. Exited with code $RET"
		;;
	esac
}


case "$1" in
	start)
		echo 'Starting xbmc'
    		xbmc_start > /var/log/xbmc.log 2>&1 &
		;;
	stop)
		echo 'Stopping xbmc'
    		killall xbmc.bin
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac

exit 0
 
